### ISSUE TITLE
系统管理->角色管理->权限管理中分配权限未生效

### ISSUE THREAD

**Issue by PengyuDeng** [jetlinks/jetlinks-ui-vue#106]
![image](https://github.com/jetlinks/jetlinks-ui-vue/assets/89559616/5b3c332d-4568-4c9c-a900-1247d611ac9d)
点击保存后，不生效

**Comment by PengyuDeng** [comment]
{
    "menus": [
        {
            "id": "d56cfb0076ecc4ff2d8503b39b3dbf1c",
            "parentId": "9c21f88182e7cc75cbdfa8e4b7844272",
            "path": "wBTD-wNqe",
            "sortIndex": 1,
            "level": 2,
            "owner": "iot",
            "name": "首页",
            "code": "home",
            "icon": "icon-zhihuishequ",
            "url": "/iot/home",
            "options": {},
            "createTime": 1684745357433,
            "granted": true
        },
        {
            "id": "b27e972543cdc5da5730b6d4b9b537b1",
            "parentId": "9c21f88182e7cc75cbdfa8e4b7844272",
            "path": "wBTD-w4Cc",
            "sortIndex": 2,
            "level": 2,
            "owner": "iot",
            "name": "通知管理",
            "code": "notice",
            "icon": "icon-tongzhiguanli",
            "url": "/iot/notice",
            "options": {},
            "children": [
                {
                    "id": "09bcab0a6a1f0796075254a453139287",
                    "parentId": "b27e972543cdc5da5730b6d4b9b537b1",
                    "path": "wBTD-w4Cc-f1Og",
                    "sortIndex": 1,
                    "level": 3,
                    "owner": "iot",
                    "name": "通知配置",
                    "code": "notice/Config",
                    "icon": "icon-tongzhiguanli",
                    "url": "/iot/notice/Config",
                    "buttons": [
                        {
                            "id": "bind",
                            "name": "同步用户",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "view",
                            "name": "查看",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "log",
                            "name": "通知记录",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "debug",
                            "name": "调试",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "export",
                            "name": "导出",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "import",
                            "name": "导入",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "delete",
                            "name": "删除",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "update",
                            "name": "编辑",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "add",
                            "name": "新增",
                            "enabled": true,
                            "granted": true
                        }
                    ],
                    "options": {},
                    "createTime": 1684745357433,
                    "granted": true
                },
                {
                    "id": "705b82c807fa18360bf62a2b35f454e9",
                    "parentId": "b27e972543cdc5da5730b6d4b9b537b1",
                    "path": "wBTD-w4Cc-KCuS",
                    "sortIndex": 2,
                    "level": 3,
                    "owner": "iot",
                    "name": "通知模板",
                    "code": "notice/Template",
                    "icon": "icon-tongzhiguanli",
                    "url": "/iot/notice/Template",
                    "buttons": [
                        {
                            "id": "view",
                            "name": "查看",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "log",
                            "name": "通知记录",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "debug",
                            "name": "调试",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "export",
                            "name": "导出",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "import",
                            "name": "导入",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "delete",
                            "name": "删除",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "update",
                            "name": "编辑",
                            "enabled": true,
                            "granted": true
                        },
                        {
                            "id": "add",
                            "name": "新增",
                            "enabled": true,
                            "granted": true
                        }
                    ],
                    "options": {},
                    "createTime": 1684745357433,
                    "granted": true
                }
            ],
            "createTime": 1684745357433,
            "granted": true
        },
        {
            "id": "09bcab0a6a1f0796075254a453139287",
            "parentId": "b27e972543cdc5da5730b6d4b9b537b1",
            "path": "wBTD-w4Cc-f1Og",
            "sortIndex": 1,
            "level": 3,
            "owner": "iot",
            "name": "通知配置",
            "code": "notice/Config",
            "icon": "icon-tongzhiguanli",
            "url": "/iot/notice/Config",
            "buttons": [
                {
                    "id": "bind",
                    "name": "同步用户",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "view",
                    "name": "查看",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "log",
                    "name": "通知记录",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "debug",
                    "name": "调试",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "export",
                    "name": "导出",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "import",
                    "name": "导入",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "delete",
                    "name": "删除",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "update",
                    "name": "编辑",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "add",
                    "name": "新增",
                    "enabled": true,
                    "granted": true
                }
            ],
            "options": {},
            "createTime": 1684745357433,
            "granted": true
        },
        {
            "id": "705b82c807fa18360bf62a2b35f454e9",
            "parentId": "b27e972543cdc5da5730b6d4b9b537b1",
            "path": "wBTD-w4Cc-KCuS",
            "sortIndex": 2,
            "level": 3,
            "owner": "iot",
            "name": "通知模板",
            "code": "notice/Template",
            "icon": "icon-tongzhiguanli",
            "url": "/iot/notice/Template",
            "buttons": [
                {
                    "id": "view",
                    "name": "查看",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "log",
                    "name": "通知记录",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "debug",
                    "name": "调试",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "export",
                    "name": "导出",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "import",
                    "name": "导入",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "delete",
                    "name": "删除",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "update",
                    "name": "编辑",
                    "enabled": true,
                    "granted": true
                },
                {
                    "id": "add",
                    "name": "新增",
                    "enabled": true,
                    "granted": true
                }
            ],
            "options": {},
            "createTime": 1684745357433,
            "granted": true
        }
    ]
}

**Comment by PengyuDeng** [comment]
再次查询，后台返回
{"message":"success","result":[{"id":"9c21f88182e7cc75cbdfa8e4b7844272","path":"wBTD","sortIndex":1,"level":1,"owner":"iot","name":"物联网","code":"iot","icon":"icon-wulianwang","url":"/iot","children":[{"id":"d56cfb0076ecc4ff2d8503b39b3dbf1c","parentId":"9c21f88182e7cc75cbdfa8e4b7844272","path":"wBTD-wNqe","sortIndex":1,"level":2,"owner":"iot","name":"首页","code":"home","icon":"icon-zhihuishequ","url":"/iot/home","options":{},"createTime":1684745357433,"granted":true},{"id":"b27e972543cdc5da5730b6d4b9b537b1","parentId":"9c21f88182e7cc75cbdfa8e4b7844272","path":"wBTD-w4Cc","sortIndex":2,"level":2,"owner":"iot","name":"通知管理","code":"notice","icon":"icon-tongzhiguanli","url":"/iot/notice","options":{},"children":[{"id":"09bcab0a6a1f0796075254a453139287","parentId":"b27e972543cdc5da5730b6d4b9b537b1","path":"wBTD-w4Cc-f1Og","sortIndex":1,"level":3,"owner":"iot","name":"通知配置","code":"notice/Config","icon":"icon-tongzhiguanli","url":"/iot/notice/Config","buttons":[{"id":"bind","name":"同步用户","enabled":true,"granted":true},{"id":"view","name":"查看","enabled":true,"granted":true},{"id":"log","name":"通知记录","enabled":true,"granted":true},{"id":"debug","name":"调试","enabled":true,"granted":true},{"id":"export","name":"导出","enabled":true,"granted":true},{"id":"import","name":"导入","enabled":true,"granted":true},{"id":"delete","name":"删除","enabled":true,"granted":true},{"id":"update","name":"编辑","enabled":true,"granted":true},{"id":"add","name":"新增","enabled":true,"granted":true}],"options":{},"createTime":1684745357433,"granted":true},{"id":"705b82c807fa18360bf62a2b35f454e9","parentId":"b27e972543cdc5da5730b6d4b9b537b1","path":"wBTD-w4Cc-KCuS","sortIndex":2,"level":3,"owner":"iot","name":"通知模板","code":"notice/Template","icon":"icon-tongzhiguanli","url":"/iot/notice/Template","buttons":[{"id":"view","name":"查看","enabled":true,"granted":true},{"id":"log","name":"通知记录","enabled":true,"granted":true},{"id":"debug","name":"调试","enabled":true,"granted":true},{"id":"export","name":"导出","enabled":true,"granted":true},{"id":"import","name":"导入","enabled":true,"granted":true},{"id":"delete","name":"删除","enabled":true,"granted":true},{"id":"update","name":"编辑","enabled":true,"granted":true},{"id":"add","name":"新增","enabled":true,"granted":true}],"options":{},"createTime":1684745357433,"granted":true}],"createTime":1684745357433,"granted":true},{"id":"b6327c3ff01b49c9a7a96101606dc27a","parentId":"9c21f88182e7cc75cbdfa8e4b7844272","path":"wBTD-FTSQ","sortIndex":3,"level":2,"owner":"iot","name":"设备管理","code":"device","icon":"icon-shebei","url":"/iot/device","children":[{"id":"68a02c9efa9fb4885c89b007f97d074d","parentId":"b6327c3ff01b49c9a7a96101606dc27a","path":"wBTD-FTSQ-BKOI","sortIndex":1,"level":3,"owner":"iot","name":"仪表盘","code":"device/DashBoard","icon":"icon-keshihua","url":"/iot/device/DashBoard","createTime":1684745357433,"granted":false},{"id":"8ddbb67de5f65514105d47b448bfd70e","parentId":"b6327c3ff01b49c9a7a96101606dc27a","path":"wBTD-FTSQ-m73j","sortIndex":2,"level":3,"owner":"iot","name":"产品","code":"device/Product","icon":"icon-chanpin","url":"/iot/device/Product","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"action","name":"启/禁用","enabled":false,"granted":false},{"id":"export","name":"导出","enabled":false,"granted":false},{"id":"import","name":"导入","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"1b136e7e4e4e74bb24b91802e4cfcd2d","parentId":"b6327c3ff01b49c9a7a96101606dc27a","path":"wBTD-FTSQ-O3gl","sortIndex":3,"level":3,"owner":"iot","name":"设备","code":"device/Instance","icon":"icon-shebei","url":"/iot/device/Instance","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"export","name":"导出","enabled":false,"granted":false},{"id":"import","name":"导入","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"action","name":"启/禁用","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"bc83f18659982abb9ac1a96362fc3372","parentId":"b6327c3ff01b49c9a7a96101606dc27a","path":"wBTD-FTSQ-5urC","sortIndex":4,"level":3,"owner":"iot","name":"产品分类","code":"device/Category","icon":"icon-chanpinfenlei","url":"/iot/device/Category","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"bd55cdc9d0c1700afe628f572f91c22e","parentId":"9c21f88182e7cc75cbdfa8e4b7844272","path":"wBTD-ElNC","sortIndex":4,"level":2,"owner":"iot","name":"运维管理","code":"link","icon":"icon-yunweiguanli-1","url":"/iot/link","children":[{"id":"47bedff9df89ecc0f0ce896e53805f02","parentId":"bd55cdc9d0c1700afe628f572f91c22e","path":"wBTD-ElNC-jeiB","sortIndex":1,"level":3,"owner":"iot","name":"仪表盘","code":"link/DashBoard","icon":"icon-keshihua","url":"/iot/link/dashboard","createTime":1684745357433,"granted":false},{"id":"10e67b761ec1f4206fabf36fcf9d9b0b","parentId":"bd55cdc9d0c1700afe628f572f91c22e","path":"wBTD-ElNC-sMKM","sortIndex":2,"level":3,"owner":"iot","name":"设备接入网关","code":"link/AccessConfig","icon":"icon-wangguanzishebei","url":"/iot/link/accessConfig","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"action","name":"启/禁用","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"cdd73c8cb02d1ae9af61ded7fc31e9c5","parentId":"bd55cdc9d0c1700afe628f572f91c22e","path":"wBTD-ElNC-dlwQ","sortIndex":3,"level":3,"owner":"iot","name":"协议管理","code":"link/Protocol","icon":"icon-tongzhiguanli","url":"/iot/link/protocol","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"c340f8977e0d221da893715cab58ae8c","parentId":"bd55cdc9d0c1700afe628f572f91c22e","path":"wBTD-ElNC-PfXO","sortIndex":4,"level":3,"owner":"iot","name":"日志管理","code":"Log","icon":"icon-rizhifuwu","url":"/iot/link/Log","buttons":[],"createTime":1684745357433,"granted":false},{"id":"f99acd0b64f96209eb276236cfb427cb","parentId":"bd55cdc9d0c1700afe628f572f91c22e","path":"wBTD-ElNC-cr5x","sortIndex":5,"level":3,"owner":"iot","name":"网络组件","code":"link/Type","icon":"icon-wangluozujian","url":"/iot/link/type","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"action","name":"启/禁用","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"e395655a273a1b765236342738289587","parentId":"bd55cdc9d0c1700afe628f572f91c22e","path":"wBTD-ElNC-sUun","sortIndex":6,"level":3,"owner":"iot","name":"证书管理","code":"link/Certificate","icon":"icon-zhengshuguanli","url":"/iot/link/Certificate","buttons":[{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false},{"id":"view","name":"查看","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"6a937a565b8f85d430bc06fb622825c4","parentId":"bd55cdc9d0c1700afe628f572f91c22e","path":"wBTD-ElNC-sEQf","sortIndex":7,"level":3,"owner":"iot","name":"snmp配置","code":"link/snmp","icon":"SlidersOutlined","url":"/iot/link/snmp","createTime":1684995910351,"granted":false},{"id":"95583bec448cee6334de9e4dec85ccf6","parentId":"bd55cdc9d0c1700afe628f572f91c22e","path":"wBTD-ElNC-Fy3D","sortIndex":8,"level":3,"owner":"iot","name":"通话管理","code":"link/callManage","icon":"PlayCircleOutlined","url":"/iot/link/callManage","createTime":1685433698651,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"3c7dca6ea8b5828bbcc023ce905244f7","parentId":"9c21f88182e7cc75cbdfa8e4b7844272","path":"wBTD-w7eI","sortIndex":5,"level":2,"owner":"iot","name":"告警中心","code":"rule-engine/Alarm","icon":"icon-shebeigaojing","url":"/iot/Alarm","buttons":[],"children":[{"id":"f4d6880e3d8b3e3234c547fa84856b32","parentId":"3c7dca6ea8b5828bbcc023ce905244f7","path":"wBTD-w7eI-cQbu","sortIndex":1,"level":3,"owner":"iot","name":"仪表盘","code":"rule-engine/DashBoard","icon":"icon-keshihua","url":"/iot/Alarm/dashboard","buttons":[],"createTime":1684745357433,"granted":false},{"id":"f1b83487813173403cb117970b9801ae","parentId":"3c7dca6ea8b5828bbcc023ce905244f7","path":"wBTD-w7eI-S7OB","sortIndex":1,"level":3,"owner":"iot","name":"仪表盘_test","code":"rule-engine/DashBoard1","icon":"PieChartOutlined","url":"/iot/Alarm/dashboard1","createTime":1685429017495,"granted":false},{"id":"af160284d1934bf052a2eeb9b9a9cb8f","parentId":"3c7dca6ea8b5828bbcc023ce905244f7","path":"wBTD-w7eI-icBY","sortIndex":2,"level":3,"owner":"iot","name":"基础配置","code":"rule-engine/Alarm/Config","icon":"icon-chajianguanli","url":"/iot/Alarm/Config","buttons":[{"id":"update","name":"保存","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"c5d3b1261f2f414dd04b0bf9194aa29e","parentId":"3c7dca6ea8b5828bbcc023ce905244f7","path":"wBTD-w7eI-SMmh","sortIndex":3,"level":3,"owner":"iot","name":"告警配置","code":"rule-engine/Alarm/Configuration","icon":"icon-warning_amber","url":"/iot/Alarm/Configuration","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false},{"id":"action","name":"启/禁用","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"tigger","name":"手动触发","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"fca24d8d3276a410f7031a9b721017fd","parentId":"3c7dca6ea8b5828bbcc023ce905244f7","path":"wBTD-w7eI-Mcji","sortIndex":4,"level":3,"owner":"iot","name":"告警记录","code":"rule-engine/Alarm/Log","icon":"icon-changjingliandong","url":"/iot/Alarm/Log","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"action","name":"告警处理","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"91aa7c753b1c030dfad612aa0a45d453","parentId":"9c21f88182e7cc75cbdfa8e4b7844272","path":"wBTD-lTVA","sortIndex":7,"level":2,"owner":"iot","name":"规则引擎","code":"rule-engine","icon":"icon-zidingyiguize","url":"/iot/rule-engine","buttons":[],"children":[{"id":"b68867fdc24cfc3df7c52e842136f439","parentId":"91aa7c753b1c030dfad612aa0a45d453","path":"wBTD-lTVA-PQUi","sortIndex":2,"level":3,"owner":"iot","name":"场景联动","code":"rule-engine/Scene","icon":"icon-yunweiguanli-1","url":"/iot/rule-engine/scene","buttons":[{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"tigger","name":"手动触发","enabled":false,"granted":false},{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"action","name":"启用/禁用","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false}],"createTime":1684745357433,"granted":false}],"createTime":1684745357347,"granted":true},{"id":"fd1670b860ae58cc58bcd01d027ccd35","path":"0O3d","sortIndex":3,"level":1,"owner":"iot","name":"系统管理","code":"system","icon":"icon-xitongguanli1","url":"/system","buttons":[],"children":[{"id":"96e4bd287adbe0486e2168c59450841f","parentId":"fd1670b860ae58cc58bcd01d027ccd35","path":"0O3d-8xBc","sortIndex":1,"level":2,"owner":"iot","name":"基础配置","code":"system/Basis","icon":"icon-shezhi","url":"/system/Basis","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"update","name":"保存","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"fe2e557bcf09a5503cbb5bebeb0b7f1c","parentId":"fd1670b860ae58cc58bcd01d027ccd35","path":"0O3d-VMBC","sortIndex":2,"level":2,"owner":"iot","name":"用户管理","code":"system/User","icon":"icon-yonghuguanli","url":"/system/user","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"action","name":"启/禁用","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"3962ec0835f3b4a68c1f63b955625046","parentId":"fd1670b860ae58cc58bcd01d027ccd35","path":"0O3d-6PIK","sortIndex":3,"level":2,"owner":"iot","name":"组织管理","code":"system/Department","icon":"icon-bumenguanli","url":"/system/Department","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"bind","name":"资产解绑","enabled":false,"granted":false},{"id":"bind-user","name":"绑定用户","enabled":false,"granted":false},{"id":"assert","name":"资产分配","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"9d1e96f17649ef5e7b8e7c6bb8e7b775","parentId":"fd1670b860ae58cc58bcd01d027ccd35","path":"0O3d-9skK","sortIndex":4,"level":2,"owner":"iot","name":"角色管理","code":"system/Role","icon":"icon-jiaoseguanli","url":"/system/Role","buttons":[{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false},{"id":"view","name":"查看","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"dcb6fa15da2eae8a4fdb71755edbc2bb","parentId":"fd1670b860ae58cc58bcd01d027ccd35","path":"0O3d-9Thh","sortIndex":5,"level":2,"owner":"iot","name":"菜单管理","code":"system/Menu","icon":"icon-caidanguanli","url":"/system/Menu","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false}],"createTime":1684745357433,"granted":false},{"id":"da14fad88888dc13024e8261ff8fc2b5","parentId":"fd1670b860ae58cc58bcd01d027ccd35","path":"0O3d-eHW3","sortIndex":6,"level":2,"owner":"iot","name":"权限管理","code":"system/Permission","icon":"icon-quanxianguanli","url":"/system/Permission","buttons":[{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"action","name":"启/禁用","enabled":false,"granted":false},{"id":"export","name":"导出","enabled":false,"granted":false},{"id":"import","name":"导入","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false}],"createTime":1684745357434,"granted":false},{"id":"2fa02b8758fe82a6b9666f4ebb1bbd03","parentId":"fd1670b860ae58cc58bcd01d027ccd35","path":"0O3d-LWN4","sortIndex":8,"level":2,"owner":"iot","name":"关系配置","code":"system/Relationship","icon":"icon-shuxingpeizhi","url":"/system/Relationship","buttons":[{"id":"update","name":"编辑","enabled":false,"granted":false},{"id":"delete","name":"删除","enabled":false,"granted":false},{"id":"view","name":"查看","enabled":false,"granted":false},{"id":"add","name":"新增","enabled":false,"granted":false}],"createTime":1684745357434,"granted":false}],"createTime":1684745357352,"granted":false},{"id":"23a1f2c7123e56731f890","path":"5zqE","sortIndex":9998,"level":1,"name":"通知订阅","code":"message-subscribe","url":"/message-subscribe","buttons":[{"id":"message-subscribe-view","name":"查看","enabled":false,"granted":false}],"createTime":1684745357352,"granted":false},{"id":"19a1f2c763e1231f1e1","path":"vFuI","sortIndex":9999,"level":1,"name":"个人中心","code":"account-center","url":"/user-center","buttons":[{"id":"user-center-passwd-update","name":"修改密码","enabled":false,"granted":false}],"createTime":1684745357352,"granted":false}],"status":200,"timestamp":1685667755694}

**Comment by XieYongHong** [comment]
什么不生效，是前端回显，还是已勾选的权限控制未生效，前端版本是多少，是否为社区版

**Comment by PengyuDeng** [comment]
> 什么不生效，是前端回显，还是已勾选的权限控制未生效，前端版本是多少，是否为社区版

假如有ABC三个页面，需要权限。
勾选权限ABC+提交，刷新页面。显示没有ABC权限。  
社区版。

**Comment by XieYongHong** [comment]
已修复
