### ISSUE TITLE
Invalid command: on-resolve [plugin JavaScript plugins]

### ISSUE THREAD

**Issue by CX330-jiuxi** [jetlinks/jetlinks-ui-vue#112]
<img width="927" alt="image" src="https://github.com/jetlinks/jetlinks-ui-vue/assets/51979013/e0050419-3b00-44f4-8a0f-2fcf5055addf">

**Comment by XieYongHong** [comment]
Node版本号是多少呢？

**Comment by CX330-jiuxi** [comment]
@XieYongHong 
<img width="278" alt="image" src="https://github.com/jetlinks/jetlinks-ui-vue/assets/51979013/28f1aee2-4244-4b8c-8b2d-56d902101888">

**Comment by XieYongHong** [comment]
删除node_modules，再重新用yarn安装试试

**Comment by CX330-jiuxi** [comment]
@XieYongHong 我换成gitee上的 antd 项目，想额外问下，github 和 gitee上jetlinks-community是否是一样的

**Comment by XieYongHong** [comment]
> @XieYongHong 我换成gitee上的 antd 项目，想额外问下，github 和 gitee上jetlinks-community是否是一样的

一样的

**Comment by CX330-jiuxi** [comment]
@XieYongHong 我链接这个测试环境“http://120.77.179.54:8844”，但是按照文档提供的登录账号无法登录
![image](https://github.com/jetlinks/jetlinks-ui-vue/assets/51979013/bb0ba24c-852d-49e4-bc6d-d7e18f777c59)

又可以测试的地址吗😂
