### ISSUE TITLE
【产品】【详情信息】的指标配置存在bug

### ISSUE THREAD

**Issue by jeasion** [jetlinks/jetlinks-ui-vue#149]
系统：MAC OS M1
环境：源码yarn dev

描述：

![bd050c63adb8b6dac853801f3da683ad](https://github.com/jetlinks/jetlinks-ui-vue/assets/20871774/6f327a8b-3053-4af9-872b-6e3fc22b9c47)

**Comment by XieYongHong** [comment]
已修复
