### ISSUE TITLE
产品/设备详情无法打开

### ISSUE THREAD

**Issue by MoonBottle** [jetlinks/jetlinks-ui-vue#283]
本地启动
node 版本：18.14.0
操作系统：win11
代码分支：master 最新代码

访问产品详情/设备详情控制台报错如下：
Failed to fetch dynamically imported module
报错截图：
![image](https://github.com/jetlinks/jetlinks-ui-vue/assets/12904505/38d63b64-72e8-435c-a35f-0f4421920c9c)

**Comment by XieYongHong** [comment]
清理浏览器缓存
