### ISSUE TITLE
yarn 执行报错502 Bad Gateway

### ISSUE THREAD

**Issue by yongxiangzheng** [jetlinks/jetlinks-ui-vue#292]
![image](https://github.com/jetlinks/jetlinks-ui-vue/assets/8653159/700f8e96-f450-440d-a68d-45d7f680249d)
yarn 执行报错，请问这个是依赖的地址已经无效了吗？
代码是master分支最新的代码

**Comment by 1032434056** [comment]
试试用pnpm吧
#如果未安装pnpm则安装pnpm  
npm install pnpm -g
#安装依赖
pnpm install
#启动
pnpm run dev

**Comment by yongxiangzheng** [comment]
当时我删除yarn.lock文件，再重新执行yarn就可以了
