### ISSUE TITLE
安装依赖失败

### ISSUE THREAD

**Issue by z514987467** [jetlinks/jetlinks-ui-vue#78]
在执行yarn时，报如下错误
error http://47.108.170.157:9013/jetlinks-ui-components/-/jetlinks-ui-components-1.0.5.tgz: Integrity check failed for "jetlinks-ui-components" (computed integrity doesn't match our records, got "sha512-NFjJRwFuluUEAuFguyLYidgFy3tDuh1
lKg10uBR//zFxmIzRaGPNN1r9nt/hp3BIGdQLJHUKgDJXQX6fZmfARg== sha1-3YZkR1bWBExIQhk+pyM1aIz6d9U=")

**Comment by XieYongHong** [comment]
jetlinks-ui-components已更新至npm仓库，删除项目中的.npmrc文件。重新执行yarn add jetlinks-ui-components@latest

**Comment by yongxiangzheng** [comment]
删除.npmrc文件,同时清空缓存，再add，还是出现完整性检测错误：error https://registry.jetlinks.cn/jetlinks-ui-components/-/jetlinks-ui-components-1.0.5.tgz: Integrity check failed for "jetlinks-ui-components" (computed integrity doesn't match our records, got "sha512-ZcR0ukT9bZn2syyOk9lKjjZ1cHpmMBvdHuTqayZgXwq6+pZSM5nqtVMgdUu0AXQ+pL0KbWes4L0NweYSW7XJOg== sha1-+Rp+HgxyrdzG8srbJgA5AQxIHq8=")

**Comment by XieYongHong** [comment]
重新执行yarn add jetlinks-ui-components@latest；完整性检测错误是组件库的package.json额外引入了 jetlinks-ui-components导致
