### ISSUE TITLE
设备管理里设置属性至设备

### ISSUE THREAD

**Issue by PengyuDeng** [jetlinks/jetlinks-ui-vue#81]
![Snipaste_2023-04-21_11-08-17](https://user-images.githubusercontent.com/89559616/233531488-64977972-7c9a-46f5-9e7e-c4abadd94579.jpg)
页面：设备管理-设备-运行状态
遇见问题：点击修改设备属性，如果后台上报数据导致数据更新，那么这个输入框输入的内容会因为后台更新而消失。如果是毫秒级更新数据，那么导致这个输入框一直闪烁而无法输入数据。

**Comment by bestfeng1020** [comment]
VUE版本问题已修复
